### PR TITLE
refactor: Update imap-codec and use new poison feature

### PR DESCRIPTION
**Pull request by jakoschiko**

### CODE REVIEW

**Comment by jakoschiko** [comment]
Depends on https://github.com/duesee/imap-codec/pull/592

**Comment by soywod** [comment]
> Depends on [duesee/imap-codec#592](https://github.com/duesee/imap-codec/pull/592)

The PR was merged, so I guess this one can be merged too?

**Comment by jakoschiko** [comment]
Is there another alpha release of imap-codec that we can depend on?

**Comment by jakoschiko** [comment]
@duesee Any objections on creating another imap-codec release to unblock this PR?

**Comment by duesee** [comment]
Nope, will do 👍🏻

**Comment by duesee** [comment]
* https://crates.io/crates/imap-types/versions
* https://crates.io/crates/imap-codec/versions

**Comment by soywod** [comment]
Awesome! So this PR can be merged now?

**Pull request merged**
